### ISSUE TITLE
I got the dll file, why does it not detect it?

### ISSUE THREAD

**Issue by Stevelocks100** [Retro64Mod/libsm64-retro64#12]
On mac, I have managed to get the dll file (thanks it worked!), and it still says that it "may not work properly" when minecraft is loaded up. I have the .z64, the .dll (tried changing it to .so and .dylib, no changes), the newest jar, 1.18 forge and genfiles.exe (despite it likely not working on mac). Is this because the mod is looking in %appdata% and .minecraft ? if so, it should also look for ~/Library/Application Support/minecraft/mods/sm64.dll (the pathname if that helps) if it cannot find c:%appdata%. I'm fine with no sound, so nothing need to be changed in the genfiles.

**Comment by dylanpdx** [comment]
Please try the newest release of the mod (1.0.7) Which no longer needs the DLL in the mods folder to work.
