### ISSUE TITLE
I don't get it

### ISSUE THREAD

**Issue by sanamasako** [Retro64Mod/libsm64-retro64#25]
I built it... nothing happened. I don't know what to do. No export files or nothing, it just... built. That or it pretended to.

**Comment by dylanpdx** [comment]
What are you trying to do? If this is for installing the mod, there's updated instructions here, as it no longer needs to be built to be playable: https://retro64mod.github.io/
![image](https://github.com/Retro64Mod/libsm64-retro64/assets/1337360/aecec533-e25e-4e44-9bf3-ac33bfdcba2c)
