### ISSUE TITLE
Fatal crash upon entering Mario Mode on Linux

### ISSUE THREAD

**Issue by itShirb** [Retro64Mod/libsm64-retro64#3]
Hello, I'm having an issue with the mod. After some trial and error with getting the whole thing set up i finally figured out that I needed to compile the .so from here rather than use the .dll
The issue I'm having is upon starting the game and pressing M to switch to mario mode, the game locks up and crashes with a fatal error. I'm not sure if this is the right place to report issues about the mod itself, however the other repos in the Retro64Mod organization lack an issue page.

Error Log (file created at .minecraft root as hs_err_pid39192.log upon crash):
[hs_err_pid38182.log](https://github.com/Retro64Mod/libsm64-retro64/files/8401542/hs_err_pid38182.log)

File structure:
![image](https://user-images.githubusercontent.com/69372252/161360186-6f011364-ee4e-49db-a3de-1a2e8c86e907.png)

Linux version:
5.10.88-2-lts (Arch)

**Comment by wwboyer** [comment]
I think this is likely a problem with the Retro64 plugin trying to execute `genfiles.exe` on a Linux system. Unfortunately, as of right now, the only solution is to delete `genfiles.exe` and live without working audio on Linux, as even if it were able to extract the audio from the ROM properly, the current version of libsm64 in this repo doesn't support audio on Linux anyway.

**Comment by itShirb** [comment]
Alright, so how would I go about grabbing the version from the pull request, and would I need to modify the minecraft plugin myself or is that something you have?

**Comment by wwboyer** [comment]
For the pull request, you can just go [here](https://github.com/wwboyer/libsm64-retro64/tree/linux-audio), clone the repository, and run `make` just like you did previously. As for the minecraft plugin, you would need to modify that yourself, but it's not that difficult. What I ended up doing was modifying the `extractToTmp` method in `/src/main/java/com/dylanpdx/retro64/assetsExtract.java` such that:

- the first line of the method is changed to `var tempDir = Path.of("mods","retro64");`
- every subsequent line is commented out *except* for the last line (`return tempDir.toString();`)

I then went into my mods directory and created a folder called `retro64`. Then, you clone the [sm64_asset_builder](https://github.com/Retro64Mod/sm64_asset_builder) repo (I just cloned it into `~/Documents`), place your `baserom.us.z64` file in the newly made `sm64_asset_builder` folder, then run `./genfiles.sh` (it might give you an error saying `operation not permitted`. if it does, just mark the script as executable with `chmod +x genfiles.sh` and try again). Once it finishes generating the audio files, move the following 4 files (and *only* these four files) into the `retro64` folder you created earlier:

- `bank_sets`
- `sequences.bin`
- `sound_data.ctl`
- `sound_data.tbl`

From there, the audio should hopefully work as expected, but your mileage may vary. I see no reason why this wouldn't work for you if it didn't for me, but it might not.

**Comment by itShirb** [comment]
I'm having issues with the .jar.
```
> Task :compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.
```
It also says depreciated Gradle features were used in the build and is incompatible with Gradle 8.0.

Everything else is set up though, I have the audio files in the right folder and everything its just this part that is preventing me from getting it working.

**Comment by dylanpdx** [comment]
Just letting you know that the next update of the mod will support audio on Linux without a genfiles.exe required
https://github.com/Retro64Mod/libsm64-retro64/commit/846f4814014f9703f5e14a7f612886e1cb1ffa24

**Comment by itShirb** [comment]
Oh, alrighty then. May as well just wait for that.
Curious as to why it wont compile though. Thanks for your help though!
