### ISSUE TITLE
Mario is completely reset when exiting Mario Mode

### ISSUE THREAD

**Issue by jjohnsnaill** [Retro64Mod/libsm64-retro64#6]
I'd love to use this in a serious modpack, but before I can, there are several big roadblocks. One of them is that Mario's state is completely reset when exiting and re-entering Mario Mode, allowing you to restore all lost health and even prevent death.

**Comment by dylanpdx** [comment]
Please put all bug reports & suggestions in the repo linked on the website
https://github.com/Retro64Mod/Retro64Mod.github.io/issues/34
