### ISSUE TITLE
How can I compile on Mac?

### ISSUE THREAD

**Issue by Stevelocks100** [Retro64Mod/libsm64-retro64#8]
I'm unsure how to compile on Mac, because the instructions are for Linux and Windows, but not Mac.

**Comment by dylanpdx** [comment]
Unfortunately I don't own a Mac so I can't test or fix issues related to compiling on one.
If you figure it out though you'll have to rename the resulting .dylib file to have a .so extension

**Comment by EmeraldLoc** [comment]
I have gotten a Mac build to compile, however when hitting m in a world, it crashes with error code 6

**Comment by EmeraldLoc** [comment]
It worked, however is a nightmare to get compiled. Will make a pr instead for him to add macOS support

**Comment by dylanpdx** [comment]
Just letting you know adding support for audio in other OS is already in the works, but I'd appreciate instructions on how to compile a Mac build so I can do proper testing

**Comment by EmeraldLoc** [comment]
like I said, its a nightmare, I'll get it to you tmw, right know, I'm snoozing :)

**Comment by EmeraldLoc** [comment]
https://github.com/EmeraldLoc/libsm64-retro64/tree/macOS Created a new branch that fixes macOS.

**Comment by Stevelocks100** [comment]
I'm not able to use it because when I use the "brew" command, (zsh: command not found: brew) appears. I did install brew, yet it's not working. Do you know what the issue is with what I've done?

**Comment by EmeraldLoc** [comment]
install brew at https://brew.sh again, then try running brew, if it does not work, run /opt/homebrew/bin/brew and see if that
 works

**Comment by EmeraldLoc** [comment]
If it compiled, please close this issue.
